-- MySQL Script generated by MySQL Workbench
-- mié 01 may 2024 17:16:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = MRG_MyISAM
DEFAULT CHARACTER SET = cp1256;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Licence` TINYINT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Weapon` (
  `Weapon_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Damage` DECIMAL NOT NULL,
  PRIMARY KEY (`Weapon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Map` (
  `Map_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Map_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Character` (
  `Character_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Weapon_Weapon_id` INT NOT NULL,
  `Map_Map_id` INT NOT NULL,
  PRIMARY KEY (`Character_id`),
  INDEX `fk_Character_Weapon1_idx` (`Weapon_Weapon_id` ASC) VISIBLE,
  INDEX `fk_Character_Map1_idx` (`Map_Map_id` ASC) VISIBLE,
  CONSTRAINT `fk_Character_Weapon1`
    FOREIGN KEY (`Weapon_Weapon_id`)
    REFERENCES `mydb`.`Weapon` (`Weapon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Character_Map1`
    FOREIGN KEY (`Map_Map_id`)
    REFERENCES `mydb`.`Map` (`Map_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Character` (
  `User_User_id` INT NOT NULL,
  `Character_Character_id` INT NOT NULL,
  PRIMARY KEY (`User_User_id`, `Character_Character_id`),
  INDEX `fk_User_has_Character_Character1_idx` (`Character_Character_id` ASC) VISIBLE,
  INDEX `fk_User_has_Character_User1_idx` (`User_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Character_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `mydb`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Character_Character1`
    FOREIGN KEY (`Character_Character_id`)
    REFERENCES `mydb`.`Character` (`Character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
